### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by guer0125** [guer0125/flexing-your-muscles#1]
Hello,

Markbot says that it's expecting `<a href="#"><img src="images/youtube.svg" alt="YouTube"></a></li>`but i do have it in my HTML. It won't let me submit it

@thomasjbradley

**Comment by thomasjbradley** [comment]
YouTube should be spelled with a capital “T” in the alt attribute.

**Comment by guer0125** [comment]
thank you, i did that but i guess it didn't update. :) It's all good now
